# Generated by Django 4.2 on 2023-04-27 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='email',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
