# Generated by Django 4.2 on 2023-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profiles_email_alter_profiles_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
